# Generated by Django 5.1.2 on 2025-07-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre de la aseguranza', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'aseguranzas',
                'ordering': ['pk'],
                'permissions': [['autorizar_aseguranza', 'Puede Autorizar Mesas'], ['viewcrud_aseguranza', 'Puede Visualizar Mesas en el menú']],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='cobertura_dental',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo editable para la cantidad que dinero disponible por el cliente', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.CharField(blank=True, help_text='Grupo del cliente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='trabajo',
            field=models.CharField(blank=True, help_text='Trabajo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='puede_editar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aseguranza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientes', to='clinica.aseguranza'),
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependiente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='titular_relacion', to='clinica.cliente')),
                ('titular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependientes', to='clinica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gastos', to='clinica.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, help_text='Fecha del tratamiento', null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del procedimiento realizado', null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo del procedimiento', max_digits=10, null=True)),
                ('reclamo_enviado', models.BooleanField(default=False, help_text='Indica si ya se envió la información a la aseguradora')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tratamientos', to='clinica.cliente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
