# Generated by Django 5.1.2 on 2025-07-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_aseguranza_cliente_cobertura_dental_cliente_grupo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependiente',
            options={'ordering': ['pk'], 'permissions': [['autorizar_dependientes', 'Puede Autorizar Dependientes'], ['viewcrud_dependientes', 'Puede Visualizar Dependientes en el menú']], 'verbose_name': 'Dependiente', 'verbose_name_plural': 'Dependientes'},
        ),
        migrations.AlterModelOptions(
            name='gasto',
            options={'ordering': ['pk'], 'permissions': [['autorizar_gastos', 'Puede Autorizar Gastos'], ['viewcrud_gastos', 'Puede Visualizar Gastos en el menú']], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='historialmedico',
            options={'ordering': ['pk'], 'permissions': [['autorizar_historial_medico', 'Puede Autorizar Historial Medicos'], ['viewcrud_historial_medico', 'Puede Visualizar Historial Medicos en el menú']], 'verbose_name': 'Historial Medico', 'verbose_name_plural': 'Historial Medicos'},
        ),
        migrations.AlterModelTable(
            name='dependiente',
            table='dependientes',
        ),
        migrations.AlterModelTable(
            name='gasto',
            table='gastos',
        ),
        migrations.AlterModelTable(
            name='historialmedico',
            table='historial_medico',
        ),
    ]
