# Generated by Django 5.1.2 on 2025-07-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_dependiente_options_alter_gasto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aseguranza',
            options={'ordering': ['pk'], 'permissions': [['autorizar_aseguranza', 'Puede Autorizar Aseguranzas'], ['viewcrud_aseguranza', 'Puede Visualizar Aseguranzas en el menú']], 'verbose_name': 'Aseguranza', 'verbose_name_plural': 'Aseguranzas'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_celular',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero_telefonico',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
