# Generated by Django 5.1.2 on 2025-07-11 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_aseguranza_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='es_principal',
            new_name='es_titular',
        ),
        migrations.AddField(
            model_name='aseguranza',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='aseguranza',
            name='servicios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependientes', to='clinica.cliente'),
        ),
        migrations.DeleteModel(
            name='Dependiente',
        ),
    ]
