# Generated by Django 5.1.2 on 2025-07-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_rename_es_principal_cliente_es_titular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('servicios', models.JSONField(blank=True, help_text='Este campo con contenido JSON para un proceso determinado.', null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupos',
                'ordering': ['pk'],
                'permissions': [['autorizar_grupos', 'Puede Autorizar Grupos'], ['viewcrud_grupos', 'Puede Visualizar Grupos en el menú']],
            },
        ),
        migrations.AlterField(
            model_name='aseguranza',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='aseguranzas', to='clinica.grupo'),
        ),
    ]
