# Generated by Django 5.1.2 on 2025-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_grupo_alter_aseguranza_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguranza',
            name='grupos',
            field=models.ManyToManyField(related_name='aseguranzas', to='clinica.grupo'),
        ),
        migrations.AlterField(
            model_name='aseguranza',
            name='grupo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
