# Generated by Django 5.1.2 on 2025-07-17 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_aseguranza_grupos_alter_aseguranza_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_aseguranza', models.CharField(blank=True, help_text='id de con el que esta ligado la aseguranza', max_length=150, null=True)),
                ('medico', models.CharField(blank=True, help_text='Nombre del medico', max_length=150, null=True)),
                ('claim_enviado', models.FileField(upload_to='claims/enviados/')),
                ('pagos', models.FileField(upload_to='claims/pagos/')),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('fecha_reenviado', models.DateField(blank=True, null=True)),
                ('medio_de_envio', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_de_pago', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.CharField(blank=True, max_length=150, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('aseguranza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claims', to='clinica.aseguranza')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claims_paciente', to='clinica.cliente')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='claims', to='clinica.cliente')),
            ],
            options={
                'verbose_name': 'Claim',
                'verbose_name_plural': 'Claims',
                'db_table': 'claims',
                'ordering': ['pk'],
                'permissions': [['autorizar_claims', 'Puede Autorizar Claims'], ['viewcrud_claims', 'Puede Visualizar Claims en el menú']],
            },
        ),
    ]
