# Generated by Django 5.1.2 on 2025-07-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
