# Generated by Django 5.1.2 on 2025-07-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_cliente_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_enviado',
            field=models.FileField(blank=True, null=True, upload_to='claims/enviados/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='pagos',
            field=models.FileField(blank=True, null=True, upload_to='claims/pagos/'),
        ),
    ]
