# Generated by Django 5.1.2 on 2025-07-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_alter_claim_claim_enviado_alter_claim_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='cobertura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='historialmedico',
            name='deducible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
