# Generated by Django 5.1.2 on 2025-08-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_historialmedico_cobertura_historialmedico_deducible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='idx_nombre'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellido_paterno'], name='idx_apellido_paterno'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellido_materno'], name='idx_apellido_materno'),
        ),
    ]
